app/models/user.py
from app.extensions import db
from sqlalchemy.sql import func, expression

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(80), nullable=False, unique=True)
    # age = db.Column(db.Integer)
    # bio = db.Column(db.Text)
    created_at = db.Column(db.DateTime(timezone=True), server_default=func.now()) # func.now() renders as CURRENT_TIMESTAMP at table creation
    active = db.Column(db.Boolean, nullable=False, server_default=expression.true())
    # posts = db.relationship('Post', backref='user')
    # comments = db.relationship('Comment', backref='user')

    def __repr__(self):
        return f'<User {self.username}{' (inactive)' if not self.active else ''}>'

app/routes/users.py
"""Routes for CRUD operations on users in qq2."""
import flask
import flask_login
from app import models, forms
from app import extensions as ext

bp = flask.Blueprint('users', __name__)

@bp.route('/')
def index() -> flask.Response:
    """Returns a list of all users."""
    users = models.User.query.all()
    return flask.render_template('users/index.html', users=users)

@bp.route('/<int:id_>')
def get_user(id_:int) -> flask.Response:
    """Returns a specific user's profile."""
    user = ext.db.session.get(models.User, id_)
    if not user:
        return flask.redirect(flask.url_for('users.index'))
    return flask.render_template('users/user.html', user=user)

@bp.route('/<int:id_>/edit', methods=('GET', 'POST'))
@flask_login.login_required
def edit_user(id_:int) -> flask.Response:
    """Handles user profile updates."""
    if id_ != flask_login.current_user.id:
        flask.abort(403)
    user = ext.db.session.get(models.User, id_)
    if not user:
        return flask.redirect(flask.url_for('users.index'), code=403)
    form = forms.UserForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('users/edit.html',
                                         user=user,
                                         form=form)
        case 'POST':
            username = form.username.data or user.username
            email = form.email.data or user.email
            bio = form.bio.data or user.bio
            errors = False
            if len(models.User.query.filter_by(email=email).all()) > \
                    int(user.email == email): # email change = 0, no change = 1
                flask.flash('Email must be unique.')
                errors = True
            if not errors and form.validate_on_submit():
                user.username = username
                user.email = email
                user.bio = bio
                ext.db.session.add(user)
                ext.db.session.commit()
                flask.flash(f'User {username} updated successfully.')
                return flask.redirect(flask.url_for('users.get_user',
                                                    id_=user.id))
            return flask.render_template('users/edit.html',
                                         user=user,
                                         form=form), 400
        case _:
            flask.abort(405)

@bp.post('/<int:id_>/delete/')
@flask_login.login_required
def delete_user(id_:int) -> flask.Response:
    """Handles user profile deletions."""
    if id_ != flask_login.current_user.id:
        flask.abort(403)
    user = models.User.query.get_or_404(id_)
    ext.db.session.delete(user)
    ext.db.session.commit()
    return flask.redirect(flask.url_for('users.index'))

app/users/routes.py
from flask import render_template, request, redirect, url_for, flash
from app.users import bp
from app.extensions import db
from app.models.users import User

@bp.route('/')
def index():
    users = User.query.all()
    return render_template('users/index.html', users=users)

@bp.route('/<int:id>/')
def user(id):
    user = User.query.get_or_404(id)
    return render_template('users/user.html', user=user)

@bp.route('/<int:id>/edit/', methods=('GET', 'POST'))
def edit(id):
    user = User.query.get_or_404(id)
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        bio = request.form['bio']
        errors = False
        if len(User.query.filter_by(username=username).all()) > int(user.username == username):
            flash('Username should be unique.')
            errors = True
        if len(User.query.filter_by(email=email).all()) > int(user.email == email):
            flash('Email must be unique.')
            errors = True
        if not errors:
            user.username = username
            user.email = email
            user.bio = bio
            db.session.add(user)
            db.session.commit()
            flash(f'User {username} updated successfully.')
        return redirect(url_for('users.user', id=user.id))
    return render_template('users/edit.html', user=user)

@bp.post('/<int:id>/delete/')
def delete(id):
    user = User.query.get_or_404(id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('users.index'))

app/templates/users/edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} Edit User {% endblock %}</h1>
    <hr>
    <form method="post">
        {{ form.csrf_token }}

        <h5>{{ form.email.label(class='form-label') }}</h5>
        <p>{{ form.email(class='form-control', size=80, value=user.email) }}</p>

        <h5>{{ form.username.label(class='form-label') }}</h5>
        <p>{{ form.username(class='form-control', size=80, value=user.username) }}</p>

        <h5>{{ form.bio.label(class='form-label') }}</h5>
        <p><textarea class='form-control' id='bio' name='bio'>{{ user.bio }}</textarea></p>
        {# ^ https://stackoverflow.com/a/53126855/3178898 #}

        <p><button type="submit" class="btn btn-primary">Update Account</button></p>
    </form>
    <hr>
    <form method="post" action="{{ url_for('users.delete_user', id_=user.id) }}">
        <input type="submit" value="Delete Account" class="btn btn-danger"
               onclick="return confirm('Delete user forever?')">
    </form>
{% endblock %}

app/templates/users/index.html
{% from 'macros.html' import display_users %}
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 👥 {% endblock %} Users</h1>
    <hr>
    {{ display_users(users) }}
{% endblock %}

app/templates/users/user.html
{% extends 'base.html' %}

{% block content %}
    <h1>👤 {% block title %}{{ user.username }}{% endblock %}</h1>
    <hr>
    <p><b>Email:</b> {{ user.email }}</p>
    <p><b>Bio:</b> 
        {% if user.bio and user.bio|length > 0 %}
            {{ user.bio }}
        {% else %}
            <i>None</i>
        {% endif %}</p>
    <p><b>Joined:</b> {{ user.created_at }}</p>
    {% if current_user.is_authenticated and current_user.id == user.id %}
        <hr>
        <a class="btn btn-warning" 
            href="{{ url_for('users.edit_user', id_=user.id) }}">Edit User</a>
    {% endif %}
{% endblock %}