app/models/post.py
from app.extensions import db
from sqlalchemy.sql import func

post_tag = db.Table('post_tag',
                    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')))

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    content = db.Column(db.Text)
    created_at = db.Column(db.DateTime(timezone=True), server_default=func.now())
    comments = db.relationship('Comment', backref='post')
    tags = db.relationship('Tag', secondary=post_tag, backref='posts')

    def __repr__(self):
        return f'<Post {self.id}: "{self.title}">'

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)

    def __repr__(self):
        return f'<Tag "{self.name}">'

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text)
    created_at = db.Column(db.DateTime(timezone=True), server_default=func.now())
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))

    def __repr__(self):
        return f'<Comment {self.id}: "{self.content[:20]}{'...' if len(self.content) > 20 else ''}">'

app/posts/routes.py
from flask import render_template, request, flash, redirect, url_for
from app.posts import bp
from app.extensions import db
from app.models.posts import Post, Tag, Comment

@bp.route('/')
def index():
    posts = Post.query.all()
    return render_template('posts/index.html', posts=posts)

@bp.route('/<int:id>/')
def post(id):
    post = Post.query.get_or_404(id)
    return render_template('posts/post.html', post=post)

@bp.route('/tags/')
def tags():
    tags = Tag.query.all()
    return render_template('posts/tags.html', tags=tags)

@bp.route('/tags/<name>/')
def tag(name):
    tag = Tag.query.filter_by(name=name).first_or_404()
    return render_template('posts/tag.html', tag=tag)

@bp.route('/comments/')
def comments():
    comments = Comment.query.all()
    return render_template('posts/comments.html', comments=comments)

@bp.post('/<int:id>/comment/')
def add_comment(id):
    post = Post.query.get_or_404(id)
    content = request.form['content']
    if len(content) == 0:
        flash('Comment cannot be blank.')
    else:
        comment = Comment(content=content, post=post)
        db.session.add(comment)
        db.session.commit()
    return redirect(url_for('posts.post', id=post.id))

@bp.post('/comment/<int:id>/delete/')
def delete_comment(id):
    comment = Comment.query.get_or_404(id)
    post_id = comment.post.id
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('posts.post', id=post_id))

app/routes/auth.py
"""Routes for user authentication in qq2."""
import flask
import flask_login
import werkzeug.security as ws
from app import models, forms
from app import extensions as ext

bp = flask.Blueprint('auth', __name__)

@bp.route('/register', methods=('GET', 'POST'))
def register() -> flask.Response:
    """Handles user registrations."""
    form = forms.RegisterForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('register.html', form=form)
        case 'POST':
            email = form.email.data.strip()
            password = form.password.data.strip()
            username = form.username.data.strip()
            errors = False
            if len(models.User.query.filter_by(email=email).all()) > 0:
                flask.flash('Email must be unique.')
                errors = True
            if not errors and form.validate_on_submit():
                password = ws.generate_password_hash(password)
                user = models.User(email=email,
                                   password=password,
                                   username=username)
                ext.db.session.add(user)
                ext.db.session.commit()
                msg = f'New user registered: "{user.username}" ({user.email}).'
                flask.current_app.logger.info(msg)
                flask.flash(msg)
                return flask.redirect(flask.url_for('auth.login'))
            return flask.render_template('register.html', form=form), 400
        case _:
            flask.current_app.logger.warn(
                f'405: /auth/register: {flask.request.method}: {flask.request}')
            flask.abort(405)

@bp.route('/login', methods=('GET', 'POST'))
def login() -> flask.Response:
    """Handles user login."""
    form = forms.LoginForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('login.html', form=form)
        case 'POST':
            user_email = form.user_email.data.strip()
            password = form.password.data.strip()
            remember = form.remember.data
            errors = False
            user = models.User.query.filter(ext.db.or_(
                models.User.email==user_email,
                models.User.username==user_email)).first()
            if not user or not ws.check_password_hash(user.password, password):
                flask.flash('Invalid credentials.')
                errors = True
            if not errors and form.validate_on_submit():
                flask_login.login_user(user, remember=remember)
                msg = f'User "{user.username}" ({user.email}) logged in.'
                flask.current_app.logger.info(msg)
                flask.flash(msg)
                return flask.redirect(flask.url_for('main.index'))
            return flask.render_template('login.html', form=form), 400
        case _:
            flask.current_app.logger.warn(
                f'405: /auth/login: {flask.request.method}: {flask.request}')
            flask.abort(405)

@flask_login.login_required
@bp.route('/logout')
def logout() -> flask.Response:
    """Logs the current user out."""
    name = flask_login.current_user.username
    flask_login.logout_user()
    flask.flash(f'User {name} was logged out.')
    return flask.redirect(flask.url_for('main.index'))

app/routes/posts.py
"""Routes for post operations in qq2."""
import flask
import flask_login as fl
from app import models, forms
from app import extensions as ext

bp = flask.Blueprint('posts', __name__)

@bp.route('/')
def index() -> flask.Response:
    """Returns all posts."""
    posts = models.Post.query.all()
    return flask.render_template('posts/index.html',
                                 posts=posts,
                                 user=fl.current_user)

@bp.route('/<int:id_>')
def get_post(id_:int) -> flask.Response:
    """Returns the post specified by <id_>."""
    post = ext.db.session.get(models.Post, id_)
    if not post: return flask.redirect(flask.url_for('posts.index'))
    form = forms.CommentForm()
    return flask.render_template('posts/post.html', post=post, form=form)

# CHALLENGE: turn this into a generator function
def process_tags(tagstr:str) -> list[models.Tag] | None:
    """Converts a string of comma-separated tags into a list of db objects.

    Args:
        tagstr: A single string of comma-separated tags.

    Returns:
        A list of models.Tag objects, with their respective names set to each
        comma-separated value in the tag, or None if <tagstr> is invalid. Note
        that an empty string will also return None.
    """
    if not tagstr or len(tagstr) == 0: return None
    tags = []
    for t in tagstr.split(','):
        name = t.strip()
        tag = models.Tag.query.filter(
                models.Tag.name.ilike(name)).first() or \
                models.Tag(name=name)
        tags.append(tag)
    return tags

@bp.route('/new', methods=('GET', 'POST'))
@fl.login_required
def new_post() -> flask.Response:
    """Creates a new post."""
    form = forms.PostForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('posts/new.html', form=form)
        case 'POST':
            title = form.title.data
            content = form.content.data
            tags = process_tags(form.tags.data)
            errors = False
            if not title or not content:
                flask.flash('Post title and content required.')
                errors = True
            if not errors and form.validate_on_submit():
                post = models.Post(title=title,
                                   content=content,
                                   user_id=fl.current_user.id,
                                   tags=tags)
                ext.db.session.add(post)
                ext.db.session.commit()
                return flask.redirect(flask.url_for('posts.get_post',
                                                    id_=post.id))
            return flask.render_template('posts/new.html', form=form), 400
        case _:
            flask.current_app.logger.warning(
                f'/posts/new: {flask.request.method}: {flask.request}')
            flask.abort(405)

@bp.route('/<int:id_>/edit', methods=('GET', 'POST'))
@fl.login_required
def edit_post(id_:int) -> flask.Response:
    """Updates the post specified by <id_> if the current user wrote it."""
    post = ext.db.session.get(models.Post, id_)
    if not post:
        return flask.redirect(flask.url_for('posts.index'), code=403)
    if not fl.current_user or post.user_id != fl.current_user.id:
        flask.abort(403)
    form = forms.PostForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('posts/edit.html',
                                         post=post,
                                         form=form)
        case 'POST':
            if form.validate_on_submit():
                post.title = form.title.data or post.title
                post.content = form.content.data or post.content
                post.tags = process_tags(form.tags.data) or post.tags
                ext.db.session.add(post)
                ext.db.session.commit()
                return flask.redirect(flask.url_for('posts.get_post',
                                      id_=post.id))
            return flask.render_template('posts/edit.html',
                                         post=post,
                                         form=form), 400
        case _:
            flask.current_app.logger.warning(
                f'/posts/new: {flask.request.method}: {flask.request}')
            flask.abort(405)

@bp.post('/<int:id_>/delete')
@fl.login_required
def delete_post(id_:int) -> flask.Response:
    """Deletes the post specified by <id_> and its associated comments."""
    post = models.Post.query.filter_by(id=id_).first_or_404()
    if post.user.id != fl.current_user.id:
        flask.abort(403)
    ext.db.session.delete(post)
    ext.db.session.commit()
    return flask.redirect(flask.url_for('posts.index'))

@bp.route('/tags/')
def get_tags() -> flask.Response:
    """Returns all tags."""
    tags = models.Tag.query.all()
    return flask.render_template('posts/tags.html', tags=tags)

@bp.route('/tags/<name>')
def get_tag(name:str) -> flask.Response:
    """Returns all posts for tag <name>."""
    tag = models.Tag.query.filter_by(name=name).first_or_404()
    return flask.render_template('posts/tag.html', tag=tag)

@bp.route('/comments/')
def get_comments() -> flask.Response:
    """Returns all comments."""
    comments = models.Comment.query.all()
    return flask.render_template('posts/comments.html', comments=comments)

@bp.post('/<int:id_>/comments/add')
@fl.login_required
def add_comment(id_:int) -> flask.Response:
    """Adds a comment to the post specified by <id_>."""
    post = models.Post.query.filter_by(id=id_).first_or_404()
    form = forms.CommentForm()
    content = form.content.data
    errors = False
    code = 400 # catch errors for testing
    if content is None or len(content) == 0:
        flask.flash("Can't reply with empty comment.")
        errors = True
    if not errors and form.validate_on_submit():
        comment = models.Comment(content=content.strip(),
                                 post=post,
                                 user=fl.current_user)
        ext.db.session.add(comment)
        ext.db.session.commit()
        code = 302 # default for redirect()
    return flask.redirect(flask.url_for('posts.get_post', id_=post.id),
                          code=code)

@bp.route('/comments/<int:id_>/edit', methods=('GET', 'POST'))
@fl.login_required
def edit_comment(id_:int) -> flask.Response:
    """Updates the comment specified by <id_>."""
    comment = ext.db.session.get(models.Comment, id_)
    if not comment:
        return flask.redirect(flask.url_for('posts.index'))
    if not fl.current_user or comment.user_id != fl.current_user.id:
        flask.abort(403)
    form = forms.CommentForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('/posts/edit-comment.html',
                                         post=comment.post,
                                         comment=comment,
                                         form=form)
        case 'POST':
            content = form.content.data
            errors = False
            code = 400 # catch errors for testing
            if content is None or len(content) == 0:
                flask.flash("Can't update with empty comment.")
                errors = True
            if not errors and form.validate_on_submit():
                comment.content = form.content.data.strip()
                ext.db.session.add(comment)
                ext.db.session.commit()
                code = 302 # default for redirect()
            return flask.redirect(flask.url_for('posts.get_post',
                                                id_=comment.post.id), code=code)
        case _:
            flask.current_app.logger.warning(
                f'/comments/edit: {flask.request.method}: {flask.request}')
            flask.abort(405)

@bp.post('/comments/<int:id_>/delete')
@fl.login_required
def delete_comment(id_:int) -> flask.Response:
    """Deletes the comment specified by <id_>."""
    comment = models.Comment.query.filter_by(id=id_).first_or_404()
    if comment.user.id != fl.current_user.id:
        flask.abort(403)
    post_id = comment.post.id
    ext.db.session.delete(comment)
    ext.db.session.commit()
    return flask.redirect(flask.url_for('posts.get_post', id_=post_id))

app/templates/posts/comments.html
{% from 'macros.html' import display_comment_actions %}
{% extends 'base.html'%}

{% block content %}
    <h1>{% block title %} 💬 {% endblock %} Comments</h1>
    <hr>
    {% for comment in comments %}
    <div class="card" style="margin: 8px 0px">
        <div class="card-header">
            <p class="card-text">
                <i>Comment by 
                    <a href="{{ url_for('users.get_user', id_=comment.user.id) }}">{{ comment.user.username }}</a> on 
                    <a href="{{ url_for('posts.get_post', id_=comment.post.id) }}">post #{{ comment.post_id }}</a> at 
                        {{ comment.created_at }}:</i></p>
        </div>
        <div class="card-body">
            <p class="card-text">{{ comment.content }}</p>
        </div>
        {% if current_user.is_authenticated and current_user.id == comment.user.id %}
            <div class="card-footer">
                {{ display_comment_actions(comment) }}
            </div>
        {% endif %}
    </div>
    {% endfor %}
{% endblock %}

app/templates/posts/edit-comment.html
{% from 'macros.html' import display_comment_form %}
{% extends 'base.html'%}

{% block content %}
    <h1>{% block title %} 🙊 {% endblock %} Edit Comment on {{ post.title }}</h1>
    <hr>
    {{ display_comment_form(form, comment.post, comment) }}
{% endblock %}

app/templates/posts/edit.html
{% from 'macros.html' import display_post_form %}
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 🤔 {% endblock %} Edit Post</h1>
    <hr>
    {% if current_user.is_authenticated %}
        {{ display_post_form(form, post) }}
        <hr>
        <form method="POST" action="{{ url_for('posts.delete_post', id_=post.id) }}">
            <button type="submit" class="btn btn-danger"
                onclick="return confirm('Delete this post (and its comments) forever?')">Delete Post</button>
        </form>
    {% else %}
        <p>
            Please <a href="{{ url_for('auth.login') }}">login</a> to edit this post.
        </p>
    {% endif %}
{% endblock %}

app/templates/posts/index.html
{% from 'macros.html' import display_posts %}
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 📰 {% endblock %} Posts</h1>
    <hr>
    {% if current_user.is_authenticated %}
        <a class="btn btn-success" href="{{ url_for('posts.new_post') }}">New Post</a>
        <hr>
    {% endif %}
    {{ display_posts(posts) }}
{% endblock %}

app/templates/posts/new.html
{% from 'macros.html' import display_post_form %}
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 📢 {% endblock %} New Post</h1>
    <hr>
    {% if current_user.is_authenticated %}
        {{ display_post_form(form) }}
    {% else %}
        <p>
            Please <a href="{{ url_for('auth.login') }}">login</a>
            or <a href="{{ url_for('auth.register') }}">register</a> to post.
        </p>
    {% endif %}
{% endblock %}

app/templates/posts/post.html
{% from 'macros.html' import display_tags, display_comment_actions, display_comment_form %}
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 📝 {% endblock %} Post #{{ post.id }}</h1>
    <hr>
    <h3>{{ post.title }}</h3>
    <p><i>{{ post.created_at }}</i></p>
    <h5 class="card-text">{{ post.content }}</h5>
    {% if current_user.is_authenticated and current_user.id == post.user.id %}
        <br>
        <a class="btn btn-warning" href="{{ url_for('posts.edit_post', id_=post.id) }}">Edit Post</a>
    {% endif %}
    {% if post.comments|length > 0 %}
        <hr>
        <h4>Comments</h4>
        {% for comment in post.comments %}
        <div class="card" style="margin: 8px 0px">
            <div class="card-header">
                <i>
                    <a href="{{ url_for('users.get_user', id_=comment.user.id) }}">{{ comment.user.username }}</a>
                    at {{ comment.created_at }}:
                </i>
            </div>
            <div class="card-body">
                <p class="card-text">{{ comment.content }}</p>
            </div>
            {% if current_user.is_authenticated and current_user.id == comment.user.id %}
            <div class="card-footer">
                {{ display_comment_actions(comment) }}
            </div>
        {% endif %}
        </div>
        {% endfor %}
    {% endif %}
    {% if current_user.is_authenticated %}
        <hr>
        <h4>Add Comment</h4>
        {{ display_comment_form(form, post) }}
    {% endif %}
    <hr>
    {{ display_tags(post.tags) }}
{% endblock %}

app/templates/posts/tag.html
{% from 'macros.html' import display_posts %}
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 🏷 {% endblock %} Posts Tagged With "{{ tag.name }}"</h1>
    {{ display_posts(tag.posts) }}
{% endblock %}

app/templates/posts/tags.html
{% from 'macros.html' import display_tags %}
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 🏷 {% endblock %} Tags</h1>
    <hr>
    {{ display_tags(tags) }}
{% endblock %}