app/routes/auth.py
"""Routes for user authentication in qq2."""
import flask
import flask_login
import werkzeug.security as ws
from app import models, forms
from app import extensions as ext

bp = flask.Blueprint('auth', __name__)

@bp.route('/register', methods=('GET', 'POST'))
def register() -> flask.Response:
    """Handles user registrations."""
    form = forms.RegisterForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('register.html', form=form)
        case 'POST':
            email = form.email.data.strip()
            password = form.password.data.strip()
            username = form.username.data.strip()
            errors = False
            if len(models.User.query.filter_by(email=email).all()) > 0:
                flask.flash('Email must be unique.')
                errors = True
            if not errors and form.validate_on_submit():
                password = ws.generate_password_hash(password)
                user = models.User(email=email,
                                   password=password,
                                   username=username)
                ext.db.session.add(user)
                ext.db.session.commit()
                msg = f'New user registered: "{user.username}" ({user.email}).'
                flask.current_app.logger.info(msg)
                flask.flash(msg)
                return flask.redirect(flask.url_for('auth.login'))
            return flask.render_template('register.html', form=form), 400
        case _:
            flask.current_app.logger.warn(
                f'405: /auth/register: {flask.request.method}: {flask.request}')
            flask.abort(405)

@bp.route('/login', methods=('GET', 'POST'))
def login() -> flask.Response:
    """Handles user login."""
    form = forms.LoginForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('login.html', form=form)
        case 'POST':
            user_email = form.user_email.data.strip()
            password = form.password.data.strip()
            remember = form.remember.data
            errors = False
            user = models.User.query.filter(ext.db.or_(
                models.User.email==user_email,
                models.User.username==user_email)).first()
            if not user or not ws.check_password_hash(user.password, password):
                flask.flash('Invalid credentials.')
                errors = True
            if not errors and form.validate_on_submit():
                flask_login.login_user(user, remember=remember)
                msg = f'User "{user.username}" ({user.email}) logged in.'
                flask.current_app.logger.info(msg)
                flask.flash(msg)
                return flask.redirect(flask.url_for('main.index'))
            return flask.render_template('login.html', form=form), 400
        case _:
            flask.current_app.logger.warn(
                f'405: /auth/login: {flask.request.method}: {flask.request}')
            flask.abort(405)

@flask_login.login_required
@bp.route('/logout')
def logout() -> flask.Response:
    """Logs the current user out."""
    name = flask_login.current_user.username
    flask_login.logout_user()
    flask.flash(f'User {name} was logged out.')
    return flask.redirect(flask.url_for('main.index'))

app/routes/main.py
"""The main set of routes for qq2."""
import datetime as dt
import flask

bp = flask.Blueprint('main', __name__)

@bp.route('/')
def index() -> flask.Response:
    """Returns the homepage."""
    return flask.render_template('index.html',
                                 utc_dt=dt.datetime.now(dt.timezone.utc))

@bp.route('/about')
def about() -> flask.Response:
    """Returns the about page."""
    return flask.render_template('about.html')

app/routes/posts.py
"""Routes for post operations in qq2."""
import flask
import flask_login as fl
from app import models, forms
from app import extensions as ext

bp = flask.Blueprint('posts', __name__)

@bp.route('/')
def index() -> flask.Response:
    """Returns all posts."""
    posts = models.Post.query.all()
    return flask.render_template('posts/index.html',
                                 posts=posts,
                                 user=fl.current_user)

@bp.route('/<int:id_>')
def get_post(id_:int) -> flask.Response:
    """Returns the post specified by <id_>."""
    post = ext.db.session.get(models.Post, id_)
    if not post: return flask.redirect(flask.url_for('posts.index'))
    form = forms.CommentForm()
    return flask.render_template('posts/post.html', post=post, form=form)

# CHALLENGE: turn this into a generator function
def process_tags(tagstr:str) -> list[models.Tag] | None:
    """Converts a string of comma-separated tags into a list of db objects.

    Args:
        tagstr: A single string of comma-separated tags.

    Returns:
        A list of models.Tag objects, with their respective names set to each
        comma-separated value in the tag, or None if <tagstr> is invalid. Note
        that an empty string will also return None.
    """
    if not tagstr or len(tagstr) == 0: return None
    tags = []
    for t in tagstr.split(','):
        name = t.strip()
        tag = models.Tag.query.filter(
                models.Tag.name.ilike(name)).first() or \
                models.Tag(name=name)
        tags.append(tag)
    return tags

@bp.route('/new', methods=('GET', 'POST'))
@fl.login_required
def new_post() -> flask.Response:
    """Creates a new post."""
    form = forms.PostForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('posts/new.html', form=form)
        case 'POST':
            title = form.title.data
            content = form.content.data
            tags = process_tags(form.tags.data)
            errors = False
            if not title or not content:
                flask.flash('Post title and content required.')
                errors = True
            if not errors and form.validate_on_submit():
                post = models.Post(title=title,
                                   content=content,
                                   user_id=fl.current_user.id,
                                   tags=tags)
                ext.db.session.add(post)
                ext.db.session.commit()
                return flask.redirect(flask.url_for('posts.get_post',
                                                    id_=post.id))
            return flask.render_template('posts/new.html', form=form), 400
        case _:
            flask.current_app.logger.warning(
                f'/posts/new: {flask.request.method}: {flask.request}')
            flask.abort(405)

@bp.route('/<int:id_>/edit', methods=('GET', 'POST'))
@fl.login_required
def edit_post(id_:int) -> flask.Response:
    """Updates the post specified by <id_> if the current user wrote it."""
    post = ext.db.session.get(models.Post, id_)
    if not post:
        return flask.redirect(flask.url_for('posts.index'), code=403)
    if not fl.current_user or post.user_id != fl.current_user.id:
        flask.abort(403)
    form = forms.PostForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('posts/edit.html',
                                         post=post,
                                         form=form)
        case 'POST':
            if form.validate_on_submit():
                post.title = form.title.data or post.title
                post.content = form.content.data or post.content
                post.tags = process_tags(form.tags.data) or post.tags
                ext.db.session.add(post)
                ext.db.session.commit()
                return flask.redirect(flask.url_for('posts.get_post',
                                      id_=post.id))
            return flask.render_template('posts/edit.html',
                                         post=post,
                                         form=form), 400
        case _:
            flask.current_app.logger.warning(
                f'/posts/new: {flask.request.method}: {flask.request}')
            flask.abort(405)

@bp.post('/<int:id_>/delete')
@fl.login_required
def delete_post(id_:int) -> flask.Response:
    """Deletes the post specified by <id_> and its associated comments."""
    post = models.Post.query.filter_by(id=id_).first_or_404()
    if post.user.id != fl.current_user.id:
        flask.abort(403)
    ext.db.session.delete(post)
    ext.db.session.commit()
    return flask.redirect(flask.url_for('posts.index'))

@bp.route('/tags/')
def get_tags() -> flask.Response:
    """Returns all tags."""
    tags = models.Tag.query.all()
    return flask.render_template('posts/tags.html', tags=tags)

@bp.route('/tags/<name>')
def get_tag(name:str) -> flask.Response:
    """Returns all posts for tag <name>."""
    tag = models.Tag.query.filter_by(name=name).first_or_404()
    return flask.render_template('posts/tag.html', tag=tag)

@bp.route('/comments/')
def get_comments() -> flask.Response:
    """Returns all comments."""
    comments = models.Comment.query.all()
    return flask.render_template('posts/comments.html', comments=comments)

@bp.post('/<int:id_>/comments/add')
@fl.login_required
def add_comment(id_:int) -> flask.Response:
    """Adds a comment to the post specified by <id_>."""
    post = models.Post.query.filter_by(id=id_).first_or_404()
    form = forms.CommentForm()
    content = form.content.data
    errors = False
    code = 400 # catch errors for testing
    if content is None or len(content) == 0:
        flask.flash("Can't reply with empty comment.")
        errors = True
    if not errors and form.validate_on_submit():
        comment = models.Comment(content=content.strip(),
                                 post=post,
                                 user=fl.current_user)
        ext.db.session.add(comment)
        ext.db.session.commit()
        code = 302 # default for redirect()
    return flask.redirect(flask.url_for('posts.get_post', id_=post.id),
                          code=code)

@bp.route('/comments/<int:id_>/edit', methods=('GET', 'POST'))
@fl.login_required
def edit_comment(id_:int) -> flask.Response:
    """Updates the comment specified by <id_>."""
    comment = ext.db.session.get(models.Comment, id_)
    if not comment:
        return flask.redirect(flask.url_for('posts.index'))
    if not fl.current_user or comment.user_id != fl.current_user.id:
        flask.abort(403)
    form = forms.CommentForm()
    match flask.request.method:
        case 'GET':
            return flask.render_template('/posts/edit-comment.html',
                                         post=comment.post,
                                         comment=comment,
                                         form=form)
        case 'POST':
            content = form.content.data
            errors = False
            code = 400 # catch errors for testing
            if content is None or len(content) == 0:
                flask.flash("Can't update with empty comment.")
                errors = True
            if not errors and form.validate_on_submit():
                comment.content = form.content.data.strip()
                ext.db.session.add(comment)
                ext.db.session.commit()
                code = 302 # default for redirect()
            return flask.redirect(flask.url_for('posts.get_post',
                                                id_=comment.post.id), code=code)
        case _:
            flask.current_app.logger.warning(
                f'/comments/edit: {flask.request.method}: {flask.request}')
            flask.abort(405)

@bp.post('/comments/<int:id_>/delete')
@fl.login_required
def delete_comment(id_:int) -> flask.Response:
    """Deletes the comment specified by <id_>."""
    comment = models.Comment.query.filter_by(id=id_).first_or_404()
    if comment.user.id != fl.current_user.id:
        flask.abort(403)
    post_id = comment.post.id
    ext.db.session.delete(comment)
    ext.db.session.commit()
    return flask.redirect(flask.url_for('posts.get_post', id_=post_id))

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 📖 {% endblock %} What is qqueue?</h1>
    <hr>
    <h5>
        qqueue is a Flask application written in Python 3.12.
        The goal is to create a "breakable toy" to practice web development, per Hoover & Oshineye's 
        <a href="https://www.amazon.com/Apprenticeship-Patterns-Guidance-Aspiring-Craftsman/dp/0596518382"
           target="_blank"><em>Apprenticeship Patterns: Guidance for the Aspiring Software Craftsman</em></a>.
    </h5>
    <br>
    <h5>If you want to play with the source code, it's available <a href="https://github.com/whitgroves/qq2" target="_blank">on github</a>.</h5>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <!-- meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" 
          crossorigin="anonymous">

    <title>{% block title %} {% endblock %} - qqueue v2</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">qqueue</a>
        <button class="navbar-toggler" type="button" 
                data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.index') }}">users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('posts.index') }}">posts</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.new_post') }}">new post</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('posts.get_comments') }}">comments</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('posts.get_tags') }}">tags</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.about') }}">about</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    </nav>

    <div class="container" style="margin-top: 8px">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-dark" role="alert">{{ message }}</div>
        {% endfor %}
        {% block content %} {% endblock %}
    </div>

    <!-- optional js -->
    {# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" 
            crossorigin="anonymous"></script> #}

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 🏠 {% endblock %} Home</h1>
    <hr>
    <h4>
        {% if current_user.is_authenticated %}Welcome back, {{ current_user.username }}. {% endif %}
        The current time is {{ utc_dt }} UTC.
    </h4>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 🐱‍💻 {% endblock %} Sign In</h1>
    <hr>
    <form method="post">
        {{ form.csrf_token }}

        <div class="mb-3" >
            <h5>{{ form.user_email.label(class='form-label') }}</h5>
            <p>{{ form.user_email(class='form-control', size=100) }}</p>
        </div>

        <div class="mb-3">
            <h5>{{ form.password.label(class='form-label') }}</h5>
            <p>{{ form.password(class='form-control', size=100) }}</p>
        </div>

        <div class="mb-3">
            {{ form.remember(class='form-check-input') }} {{ form.remember.label(class='form-check-label') }}
        </div>
        
        <button type="submit" class="btn btn-primary">Sign In</button>
    </form>
{% endblock %}

app/templates/macros.html
{% macro display_tags(tags) %}
    {% if tags|length == 0 %}
        <i>None</i>
    {% else %}
        {% for tag in tags %}
            <a href="{{ url_for('posts.get_tag', name=tag.name) }}">{{ tag.name }}</a>
        {% endfor %}
    {% endif %}
{% endmacro %}

{% macro display_post_stats(post) %}
    {% set n_comments = post.comments|length %}
    <a href="{{ url_for('posts.get_post', id_=post.id) }}">{{ n_comments }} Comment{% if n_comments != 1 %}s{% endif %}</a> |
    Tags: {{ display_tags(post.tags) }}
{% endmacro %}

{% macro display_posts(posts) %}
    {% for post in posts %}
        <div class="card" style="margin: 8px 0px">
            <div class="card-header">
                <h5 class="card-text">{{ post.title }}</h5>
                <p class="card-text">
                    <i>By <a href="{{ url_for('users.get_user', id_=post.user.id) }}">{{ post.user.username }}</a>
                         at {{ post.created_at }} UTC</i>
                </p>
            </div>
            <div class="card-body">
                <p class="card-text">{{ post.content }}</p>
            </div>
            <div class="card-footer">
                {{ display_post_stats(post) }}
            </div>
        </div>
    {% endfor %}
{% endmacro %}

{% macro display_users(users) %}
    {% for user in users %}
        <div class="card" style="margin: 8px 0px">
            <div class="card-header">
                <h5 class="card-title"><a href="{{ url_for('users.get_user', id_=user.id) }}">{{ user.username }}</a></h5>
            </div>
            {% if user.posts|length > 0 %}
                <ul class="list-group list-group-flush">
                    {% for post in user.posts[:3] %}
                    {% set n_comments = post.comments|length %}
                        <li class="list-group-item">
                            {{ post.title }} - <small><i>{{ display_post_stats(post) }}</i></small>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
            <div class="card-body">
                <i>No posts to show.</i>
            </div>
            {% endif %}
            <div class="card-footer">
                <p class="card-text"><b>Joined:</b> {{ user.created_at }}</p>
            </div>
        </div>
    {% endfor %}
{% endmacro %}

{% macro display_post_form(form, post=None) %}
    <form method="post">
        {{ form.csrf_token }}

        <h5>{{ form.title.label(class='form-label') }}</h5>
        <p>{{ form.title(class='form-control', size=100, value=(post.title if post else '')) }}</p>

        <h5>{{ form.content.label(class='form-label') }}</h5>
        <p><textarea class='form-control' id='content' name='content'>{{ post.content if post else ''}}</textarea></p>
        {# ^ https://stackoverflow.com/a/53126855/3178898 #}

        <h5>{{ form.tags.label(class='form-label') }}</h5>
        <p>{{ form.tags(class='form-control', size=100, value=(post.tags|join(', ') if post else '')) }}</p>

        {% set submit_text = 'Update' if post else 'Create' %}
        {% set btn_class = 'primary' if post else 'success' %}
        <p><button type="submit" class="btn btn-{{ btn_class }}">{{ submit_text }} Post</button></p>
    </form>
{% endmacro %}

{% macro display_comment_actions(comment) %}
    <div class="container">
        <div class="row row-cols-auto">
            <div class="col">
                <a href="{{ url_for('posts.edit_comment', id_=comment.id) }}" class="btn btn-warning btn-sm">Edit Comment</a>
            </div>
            <div class="col">
                <form method="post" action="{{ url_for('posts.delete_comment', id_=comment.id) }}">
                    <button type="submit" class="btn btn-danger btn-sm"
                        onclick="return confirm('Delete this comment forever?')">Delete Comment</button>
                </form>
            </div>
        </div>
    </div>
{% endmacro %}

{% macro display_comment_form(form, post, comment=None) %}
    {% set url = 'posts.edit_comment' if comment else 'posts.add_comment'%}
    {% set id_ = comment.id if comment else post.id %}
    <div class="card" style="margin: 8px 0px">
        <form method="post" action="{{ url_for(url, id_=id_) }}">
            {{ form.csrf_token }}

            <div class="card-body">
                <textarea class='form-control' id='content' name='content'>{{ comment.content if comment else ''}}</textarea>
                {# ^ https://stackoverflow.com/a/53126855/3178898 #}
            </div>

            <div class="card-footer">
                {% set btn_cls = 'primary' if content else 'success' %}
                {% set btn_txt = 'Update Comment' if comment else 'Reply to Post' %}
                <button type="submit" class="btn btn-{{ btn_cls }}">{{ btn_txt }}</button>
            </div>
        </form>
    </div>
{% endmacro %}

app/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} ✍ {% endblock %} Sign Up</h1>
    <hr>
    <form method="post">
        {{ form.csrf_token }}

        <div class="mb-3" >
            <h5>{{ form.email.label(class='form-label') }}</h5>
            <p>{{ form.email(class='form-control', size=100) }}</p>
        </div>

        <div class="mb-3">
            <h5>{{ form.password.label(class='form-label') }}</h5>
            <p>{{ form.password(class='form-control', size=100) }}</p>
        </div>

        <div class="mb-3">
            <h5>{{ form.username.label(class='form-label') }}</h5>
            <p>{{ form.username(class='form-control', size=100) }}</p>
        </div>
        
        <button type="submit" class="btn btn-success">Sign Up</button>
    </form>
{% endblock %}